FROM ubuntu:jammy-20260509

#create directory
RUN mkdir -p /opt/app

#set working directory
WORKDIR /opt/app

#copy java jdk
COPY jdk-21_linux-x64_bin.tar.gz .

# Create non-root user
RUN useradd -u 1000 -m -d /home/appuser appuser

# Set permissions
RUN chown -R appuser:appuser /opt/app

# Switch user
USER appuser

#extract jdk
RUN tar -xvzf jdk-21_linux-x64_bin.tar.gz

# Set Java environment
ENV JAVA_HOME=/opt/app/jdk-21.0.11
ENV PATH="${JAVA_HOME}/bin:${PATH}"

CMD ["bash"]
